/** Canonical list of Lombok locations used across the site.
 *  Update here and it propagates to admin autocomplete + public filters. */
export const LOMBOK_LOCATIONS = [
  'Kuta',
  'Selong Belanak',
  'Torok',
  'Sembalun',
  'Tetebatu',
  'Mataram',
  'Senggigi',
  'Mong',
  'Prabu',
  'Lenek',
  'Gerupuk',
  'Mawun',
  'Mawi',
  'Are Guling',
  'Rembitan',
  'Sengkol',
  'Pujut',
  'Praya',
  'Selong',
  'Masbagik',
  'Labuhan Lombok',
  'Jerowaru',
  'Tanjung Luar',
  'Bayan',
  'Senaru',
  'Gangga',
  'Kayangan',
  'Tanjung',
  'Pemenang',
  'Bangsal',
  'Medana',
  'Sira',
  'Ampenan',
  'Cakranegara',
  'Gerung',
  'Lembar',
  'Batulayar',
  'Ekas',
] as const;

export type LombokLocation = typeof LOMBOK_LOCATIONS[number];
